/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package train_booking_system;

import java.awt.Color;
import java.awt.Toolkit;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Set;
import java.util.Date;
import java.util.Iterator;
import javax.swing.JOptionPane;

/**
 *
 * @author W10-15082021
 */
public class Tiket_Booking extends javax.swing.JFrame {
    int itemCount;
    /**
     * Creates new form Tiket_Booking
     */
    public Tiket_Booking() {
        initComponents();
        Kembali.setEnabled(false);
        this.getContentPane().setBackground(Color.lightGray);
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Cari = new javax.swing.JButton();
        PulangPergi = new javax.swing.JCheckBox();
        Asal = new javax.swing.JComboBox<>();
        Tujuan = new javax.swing.JComboBox<>();
        Berangkat = new com.toedter.calendar.JDateChooser();
        Kembali = new com.toedter.calendar.JDateChooser();
        Kelas_Kereta = new javax.swing.JComboBox<>();
        Penumpang = new javax.swing.JTextField();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("TIKET KERETA ");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Asal");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Tanggal Berangkat");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Kelas Kereta");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Tujuan");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Tanggal Kembali");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Penumpang");

        Cari.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Cari.setText("Cari");
        Cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CariActionPerformed(evt);
            }
        });

        PulangPergi.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        PulangPergi.setText("PulangPergi");
        PulangPergi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PulangPergiActionPerformed(evt);
            }
        });

        Asal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Surabaya Kota,Surabaya", "Sidoarjo,Sidoarjo", "Pasuruan,Pasuruan", "Mojokerto,Mojokerto", "Jombang,Kabupaten Jombang", "Kertosono,Kabupaten Nganjuk", "Kediri,Kota Kediri", "Tulungagung,Kabupaten Tulungagung", "Blitar,Kota Blitar", "Malang,Kota Malang" }));
        Asal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AsalActionPerformed(evt);
            }
        });

        Tujuan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sidoarjo,Sidoarjo", "Surabaya Kota,Surabaya", "Pasuruan,Pasuruan", "Mojokerto,Mojokerto", "Jombang,Kabupaten Jombang", "Kertosono,Kabupaten Nganjuk", "Kediri,Kota Kediri", "Tulungagung,Kabupaten Tulungagung", "Blitar,Kota Blitar", "Malang,Kota Malang" }));
        Tujuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TujuanActionPerformed(evt);
            }
        });

        Kelas_Kereta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "EKONOMI", "BISNIS" }));
        Kelas_Kereta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Kelas_KeretaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Asal, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Tujuan, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(Kelas_Kereta, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Berangkat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE))
                                .addGap(50, 50, 50)
                                .addComponent(PulangPergi)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel6))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(7, 7, 7)
                                        .addComponent(Kembali, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 2, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Penumpang, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(31, 31, 31))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addComponent(Cari)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Asal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tujuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PulangPergi, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Kembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Kelas_Kereta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Penumpang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(Berangkat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(Cari)
                .addGap(140, 140, 140))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CariActionPerformed
        // TODO add your handling code here:
        try {
            //DEKLARASI DULSS
            String asl,brngkt,kls,tjn,kmbl = null,isi;
            int numpang;
        
        asl = String.valueOf(Asal.getSelectedItem());
        tjn = String.valueOf(Tujuan.getSelectedItem());
        kls = String.valueOf(Kelas_Kereta.getSelectedItem());
        numpang = Integer.valueOf(Penumpang.getText());
        
        //Bikin FORMAT TANGGAL DLU PAKE SimpleDateFormat
        SimpleDateFormat dateformat = new SimpleDateFormat("yyyy-MM-dd");
        brngkt = dateformat.format(Berangkat.getDate());
        
        
        this.setVisible(false); //TUTUP JFRAME "Tiket_Booking"
        //MENAMPILKAN JFRAME "Jadwal_Kereta"
        new Jadwal_Kereta(asl,brngkt,kls,tjn,kmbl,numpang).setVisible(true);
        
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"ISI DULU MAZZZ");
            
        }
        
    }//GEN-LAST:event_CariActionPerformed

    private void AsalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AsalActionPerformed
        // TODO add your handling code here:
        
        if (Asal.getSelectedItem().equals("Sidoarjo,Sidoarjo")){
            Tujuan.removeAllItems();
            Tujuan.addItem("Surabaya Kota,Surabaya");
            Tujuan.addItem("Pasuruan,Pasuruan");
            Tujuan.addItem("Mojokerto,Mojokerto");
            Tujuan.addItem("Jombang,Kabupaten Jombang");
            Tujuan.addItem("Kertosono,Kabupaten Nganjuk");
            Tujuan.addItem("Kediri,Kota Kediri");
            Tujuan.addItem("Blitar,Kota Blitar");
            Tujuan.addItem("Malang,Kota Malang");
            }
        else if (Asal.getSelectedItem().equals("Pasuruan,Pasuruan")){
            Tujuan.removeAllItems();
            Tujuan.addItem("Surabaya Kota,Surabaya");
            Tujuan.addItem("Sidoarjo,Sidoarjo");
            Tujuan.addItem("Mojokerto,Mojokerto");
            Tujuan.addItem("Jombang,Kabupaten Jombang");
            Tujuan.addItem("Kertosono,Kabupaten Nganjuk");
            Tujuan.addItem("Kediri,Kota Kediri");
            Tujuan.addItem("Blitar,Kota Blitar");
            Tujuan.addItem("Malang,Kota Malang");
            }
        else if (Asal.getSelectedItem().equals("Surabaya Kota,Surabaya")){
            Tujuan.removeAllItems();
            Tujuan.addItem("Pasuruan,Pasuruan");
            Tujuan.addItem("Sidoarjo,Sidoarjo");
            Tujuan.addItem("Mojokerto,Mojokerto");
            Tujuan.addItem("Jombang,Kabupaten Jombang");
            Tujuan.addItem("Kertosono,Kabupaten Nganjuk");
            Tujuan.addItem("Kediri,Kota Kediri");
            Tujuan.addItem("Blitar,Kota Blitar");
            Tujuan.addItem("Malang,Kota Malang");
            }
        else if (Asal.getSelectedItem().equals("Mojokerto,Mojokerto")){
            Tujuan.removeAllItems();
            Tujuan.addItem("Pasuruan,Pasuruan");
            Tujuan.addItem("Sidoarjo,Sidoarjo");
            Tujuan.addItem("Surabaya Kota,Surabaya");
            Tujuan.addItem("Jombang,Kabupaten Jombang");
            Tujuan.addItem("Kertosono,Kabupaten Nganjuk");
            Tujuan.addItem("Kediri,Kota Kediri");
            Tujuan.addItem("Blitar,Kota Blitar");
            Tujuan.addItem("Malang,Kota Malang");
            }
        else if (Asal.getSelectedItem().equals("Jombang,Kabupaten Jombang")){
            Tujuan.removeAllItems();
            Tujuan.addItem("Pasuruan,Pasuruan");
            Tujuan.addItem("Sidoarjo,Sidoarjo");
            Tujuan.addItem("Surabaya Kota,Surabaya");
            Tujuan.addItem("Mojokerto,Mojokerto");
            Tujuan.addItem("Kertosono,Kabupaten Nganjuk");
            Tujuan.addItem("Kediri,Kota Kediri");
            Tujuan.addItem("Blitar,Kota Blitar");
            Tujuan.addItem("Malang,Kota Malang");
            }
        else if (Asal.getSelectedItem().equals("Kertosono,Kabupaten Nganjuk")){
            Tujuan.removeAllItems();
            Tujuan.addItem("Pasuruan,Pasuruan");
            Tujuan.addItem("Sidoarjo,Sidoarjo");
            Tujuan.addItem("Surabaya Kota,Surabaya");
            Tujuan.addItem("Jombang,Kabupaten Jombang");
            Tujuan.addItem("Mojokerto,Mojokerto");
            Tujuan.addItem("Kediri,Kota Kediri");
            Tujuan.addItem("Blitar,Kota Blitar");
            Tujuan.addItem("Malang,Kota Malang");
            }
        else if (Asal.getSelectedItem().equals("Kediri,Kota Kediri")){
            Tujuan.removeAllItems();
            Tujuan.addItem("Pasuruan,Pasuruan");
            Tujuan.addItem("Sidoarjo,Sidoarjo");
            Tujuan.addItem("Surabaya Kota,Surabaya");
            Tujuan.addItem("Jombang,Kabupaten Jombang");
            Tujuan.addItem("Kertosono,Kabupaten Nganjuk");
            Tujuan.addItem("Mojokerto,Mojokerto");
            Tujuan.addItem("Blitar,Kota Blitar");
            Tujuan.addItem("Malang,Kota Malang");
            }
        else if (Asal.getSelectedItem().equals("Blitar,Kota Blitar")){
            Tujuan.removeAllItems();
            Tujuan.addItem("Pasuruan,Pasuruan");
            Tujuan.addItem("Sidoarjo,Sidoarjo");
            Tujuan.addItem("Surabaya Kota,Surabaya");
            Tujuan.addItem("Jombang,Kabupaten Jombang");
            Tujuan.addItem("Kertosono,Kabupaten Nganjuk");
            Tujuan.addItem("Kediri,Kota Kediri");
            Tujuan.addItem("Mojokerto,Mojokerto");
            Tujuan.addItem("Malang,Kota Malang");
            }
        else if (Asal.getSelectedItem().equals("Malang,Kota Malang")){
            Tujuan.removeAllItems();
            Tujuan.addItem("Pasuruan,Pasuruan");
            Tujuan.addItem("Sidoarjo,Sidoarjo");
            Tujuan.addItem("Surabaya Kota,Surabaya");
            Tujuan.addItem("Jombang,Kabupaten Jombang");
            Tujuan.addItem("Kertosono,Kabupaten Nganjuk");
            Tujuan.addItem("Kediri,Kota Kediri");
            Tujuan.addItem("Blitar,Kota Blitar");
            Tujuan.addItem("Mojokerto,Mojokerto");
            }
    }//GEN-LAST:event_AsalActionPerformed

    private void TujuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TujuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TujuanActionPerformed

    private void Kelas_KeretaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Kelas_KeretaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Kelas_KeretaActionPerformed

    private void PulangPergiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PulangPergiActionPerformed
        // TODO add your handling code here:
        if(PulangPergi.isSelected()==true){
            JOptionPane.showMessageDialog(this,"Sistem sedang dalam perbaikan");
            PulangPergi.setSelected(false);
        }
    }//GEN-LAST:event_PulangPergiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tiket_Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tiket_Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tiket_Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tiket_Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tiket_Booking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Asal;
    private com.toedter.calendar.JDateChooser Berangkat;
    private javax.swing.JButton Cari;
    private javax.swing.JComboBox<String> Kelas_Kereta;
    private com.toedter.calendar.JDateChooser Kembali;
    private javax.swing.JTextField Penumpang;
    private javax.swing.JCheckBox PulangPergi;
    private javax.swing.JComboBox<String> Tujuan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
